# permissions for end users to view marketplacedatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marketplacedataset-viewer-role
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplacedatasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplacedatasets/status
  verbs:
  - get
