# permissions for end users to view marketplacedriverhealthchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marketplacedriverhealthcheck-viewer-role
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplacedriverhealthchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplacedriverhealthchecks/status
  verbs:
  - get
