# permissions for end users to view marketplacecsidrivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marketplacecsidriver-viewer-role
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplacecsidrivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplacecsidrivers/status
  verbs:
  - get
