apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: marketplace-dataset-controller-manager-service
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    redhat.marketplace.com/name: redhat-marketplace-dataset-operator
  name: marketplace-dataset-controller-manager-service
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    control-plane: controller-manager
    redhat.marketplace.com/name: redhat-marketplace-dataset-operator
status:
  loadBalancer: {}
