
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: $(SERVICE_NAME)
spec:
  ports:
    - port: 9443
      targetPort: 9443
  selector:
    control-plane: controller-manager