## Append samples you want in your CSV to this file as resources ##
resources:
- marketplace_v1alpha1_marketplacedataset.yaml
- marketplace_v1alpha1_marketplacecsidriver.yaml
- marketplace_v1alpha1_marketplacedriverhealthcheck.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
