apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-rhm-cos-csi-role-binding
  namespace: ${NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: csi-rhm-cos
    namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: csi-rhm-cos-csi-role
  apiGroup: rbac.authorization.k8s.io