apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: olm-marketplace-dataset-leader-election-role-binding
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: olm-marketplace-dataset-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${NAMESPACE}